exports.Data=[
    {
        "Names": "JAN",
        "SDPQtyTotal": 0,
        "CRDQtyTotal": 0,
        "SDPTarget": "",
        "SDP": 0,
        "PDPTarget": "",
        "PDP": 0,
        "MDPTarget": "",
        "MDP": 0,
        "Target": "1",
        "Actual": "1",
        "Efficiency_Target": 0,
        "Efficiency_Actual": 0
    },
    {
        "Names": "FEB",
        "SDPQtyTotal": 0,
        "CRDQtyTotal": 0,
        "SDPTarget": "",
        "SDP": 0,
        "PDPTarget": "",
        "PDP": 0,
        "MDPTarget": "",
        "MDP": 0,
        "Target": "1",
        "Actual": "1",
        "Efficiency_Target": 0,
        "Efficiency_Actual": 0
    },
    {
        "Names": "MAR",
        "SDPQtyTotal": 0,
        "CRDQtyTotal": 0,
        "SDPTarget": "",
        "SDP": 0,
        "PDPTarget": "",
        "PDP": 0,
        "MDPTarget": "",
        "MDP": 0,
        "Target": "1",
        "Actual": "1",
        "Efficiency_Target": 0,
        "Efficiency_Actual": 0
    },
    {
        "Names": "APR",
        "SDPQtyTotal": 0,
        "CRDQtyTotal": 0,
        "SDPTarget": "",
        "SDP": 0,
        "PDPTarget": "",
        "PDP": 0,
        "MDPTarget": "",
        "MDP": 0,
        "Target": "1",
        "Actual": "1",
        "Efficiency_Target": 0,
        "Efficiency_Actual": 0
    },
    {
        "Names": "MAY",
        "SDPQtyTotal": 0,
        "CRDQtyTotal": 0,
        "SDPTarget": "",
        "SDP": 0,
        "PDPTarget": "",
        "PDP": 0,
        "MDPTarget": "",
        "MDP": 0,
        "Target": "1",
        "Actual": "1",
        "Efficiency_Target": 0,
        "Efficiency_Actual": 0
    },
    {
        "Names": "JUN",
        "SDPQtyTotal": 0,
        "CRDQtyTotal": 0,
        "SDPTarget": "",
        "SDP": 0,
        "PDPTarget": "",
        "PDP": 87.81,
        "MDPTarget": "",
        "MDP": 0,
        "Target": "1",
        "Actual": "1",
        "Efficiency_Target": 0,
        "Efficiency_Actual": 0
    },
    {
        "Names": "JUL",
        "SDPQtyTotal": 0,
        "CRDQtyTotal": 0,
        "SDPTarget": "",
        "SDP": 0,
        "PDPTarget": "",
        "PDP": 97.68,
        "MDPTarget": "",
        "MDP": 0,
        "Target": "1",
        "Actual": "1",
        "Efficiency_Target": 0,
        "Efficiency_Actual": 0
    },
    {
        "Names": "AUG",
        "SDPQtyTotal": 0,
        "CRDQtyTotal": 0,
        "SDPTarget": "",
        "SDP": 0,
        "PDPTarget": "",
        "PDP": 99.74,
        "MDPTarget": "",
        "MDP": 0,
        "Target": "1",
        "Actual": "1",
        "Efficiency_Target": 0,
        "Efficiency_Actual": 0
    },
    {
        "Names": "SEP",
        "SDPQtyTotal": 0,
        "CRDQtyTotal": 0,
        "SDPTarget": "",
        "SDP": 0,
        "PDPTarget": "",
        "PDP": 80.1,
        "MDPTarget": "",
        "MDP": 0,
        "Target": "1",
        "Actual": "1",
        "Efficiency_Target": 0,
        "Efficiency_Actual": 0
    },
    {
        "Names": "OCT",
        "SDPQtyTotal": 0,
        "CRDQtyTotal": 0,
        "SDPTarget": "",
        "SDP": 0,
        "PDPTarget": "",
        "PDP": 0,
        "MDPTarget": "",
        "MDP": 0,
        "Target": "1",
        "Actual": "1",
        "Efficiency_Target": 0,
        "Efficiency_Actual": 0
    },
    {
        "Names": "NOV",
        "SDPQtyTotal": 0,
        "CRDQtyTotal": 0,
        "SDPTarget": "",
        "SDP": 0,
        "PDPTarget": "",
        "PDP": 0,
        "MDPTarget": "",
        "MDP": 0,
        "Target": "1",
        "Actual": "1",
        "Efficiency_Target": 0,
        "Efficiency_Actual": 0
    },
    {
        "Names": "TOTAL",
        "SDPQtyTotal": 0,
        "CRDQtyTotal": 0,
        "SDPTarget": "",
        "SDP": 0,
        "PDPTarget": "",
        "PDP": 0,
        "MDPTarget": "",
        "MDP": 0,
        "Target": "1",
        "Actual": "1",
        "Efficiency_Target": 0,
        "Efficiency_Actual": 0
    }
]