exports.Data=[
    {
        "Num": "1",
        "id": 1452,
        "season_start": "FW",
        "year_start": "2023",
        "season_end": "SS",
        "year_end": "2024",
        "Art": "IF7004",
        "Model": "SAMBA OG W",
        "CWA": "2024/03/11",
        "Pro_Month": "6-9",
        "mcs": "OK",
        "LINE": "A4-1",
        "PRO_START_DATE": "5/13",
        "STAGE": "CS3\nFW24",
        "Material_GC": "OK",
        "cutting": "3/19",
        "mct": "3/21",
        "stitching_v": "3/23",
        "assembly_v": "3/25",
        "meeting": "",
        "on_show": "1",
        "userid": "07074",
        "userDate": "2024-03-29T15:06:50.217Z"
    },
    {
        "Num": "2",
        "id": 1453,
        "season_start": "FW",
        "year_start": "2023",
        "season_end": "SS",
        "year_end": "2024",
        "Art": "IH8559",
        "Model": "SUBZONE",
        "CWA": "2024/03/25",
        "Pro_Month": "5-8",
        "mcs": "Reference shoe",
        "LINE": "D1-6",
        "PRO_START_DATE": "Not yet receive \norder ",
        "STAGE": "CS2\nFW24",
        "Material_GC": "OK",
        "cutting": "3/20",
        "mct": "3/23",
        "stitching_v": "3/26",
        "assembly_v": "3/27",
        "meeting": "",
        "on_show": "1",
        "userid": "07074",
        "userDate": "2024-03-29T15:06:54.437Z"
    },
    {
        "Num": "3",
        "id": 1454,
        "season_start": "FW",
        "year_start": "2023",
        "season_end": "SS",
        "year_end": "2024",
        "Art": "JH7927",
        "Model": "SUBZONE J",
        "CWA": "2024/03/25",
        "Pro_Month": "5-8",
        "mcs": "Reference shoe",
        "LINE": "D1-6",
        "PRO_START_DATE": "Not yet receive \norder ",
        "STAGE": "CS2\nFW24",
        "Material_GC": "OK",
        "cutting": "3/20",
        "mct": "3/23",
        "stitching_v": "3/26",
        "assembly_v": "3/27",
        "meeting": "",
        "on_show": "1",
        "userid": "07074",
        "userDate": "2024-03-29T15:06:57.700Z"
    },
    {
        "Num": "4",
        "id": 1455,
        "season_start": "FW",
        "year_start": "2023",
        "season_end": "SS",
        "year_end": "2024",
        "Art": "IH1238",
        "Model": "BARREDA DECODE",
        "CWA": "2024/04/22",
        "Pro_Month": "7-10",
        "mcs": "Reference shoe",
        "LINE": "A-3",
        "PRO_START_DATE": "Not yet receive \norder ",
        "STAGE": "CS1\nSS25",
        "Material_GC": "OK",
        "cutting": "OK",
        "mct": "3/29",
        "stitching_v": "3/30",
        "assembly_v": "4/1",
        "meeting": "",
        "on_show": "1",
        "userid": "07074",
        "userDate": "2024-03-29T15:07:00.607Z"
    },
    {
        "Num": "5",
        "id": 1456,
        "season_start": "FW",
        "year_start": "2023",
        "season_end": "SS",
        "year_end": "2024",
        "Art": "JI2321",
        "Model": "BARREDA DECODE",
        "CWA": "2024/04/22",
        "Pro_Month": "7-10",
        "mcs": "Reference shoe",
        "LINE": "C-1",
        "PRO_START_DATE": "Not yet receive \norder ",
        "STAGE": "CS1\nSS25",
        "Material_GC": "OK",
        "cutting": "OK",
        "mct": "3/29",
        "stitching_v": "3/30",
        "assembly_v": "4/1",
        "meeting": "",
        "on_show": "1",
        "userid": "07074",
        "userDate": "2024-03-29T15:07:03.670Z"
    },
    {
        "Num": "6",
        "id": 1457,
        "season_start": "FW",
        "year_start": "2023",
        "season_end": "SS",
        "year_end": "2024",
        "Art": "JI2326",
        "Model": "BARREDA DECODED V2",
        "CWA": "2024/05/06",
        "Pro_Month": "8-10",
        "mcs": "Reference shoe",
        "LINE": "C-1",
        "PRO_START_DATE": "Not yet receive \norder ",
        "STAGE": "CS1\nSS25",
        "Material_GC": "OK",
        "cutting": "OK",
        "mct": "3/30",
        "stitching_v": "4/1",
        "assembly_v": "4/2",
        "meeting": "",
        "on_show": "1",
        "userid": "07074",
        "userDate": "2024-03-29T15:07:07.093Z"
    },
    {
        "Num": "7",
        "id": 1458,
        "season_start": "FW",
        "year_start": "2023",
        "season_end": "SS",
        "year_end": "2024",
        "Art": "IH6171",
        "Model": "COURTBLOCK BOLD",
        "CWA": "2024/05/06",
        "Pro_Month": "8-10",
        "mcs": "Reference shoe",
        "LINE": "D3-1",
        "PRO_START_DATE": "Not yet receive \norder ",
        "STAGE": "CS1\nSS25",
        "Material_GC": "OK",
        "cutting": "OK",
        "mct": "4/1",
        "stitching_v": "4/2",
        "assembly_v": "4/3",
        "meeting": "",
        "on_show": "1",
        "userid": "07074",
        "userDate": "2024-03-29T15:07:10.107Z"
    },
    {
        "Num": "8",
        "id": 1459,
        "season_start": "FW",
        "year_start": "2023",
        "season_end": "SS",
        "year_end": "2024",
        "Art": "JH8154",
        "Model": "SUPERSKATE",
        "CWA": "2024/05/20",
        "Pro_Month": "8-10",
        "mcs": "Reference shoe",
        "LINE": "D3-5",
        "PRO_START_DATE": "Not yet receive \norder ",
        "STAGE": "CS1\nSS25",
        "Material_GC": "OK",
        "cutting": "OK",
        "mct": "4/1",
        "stitching_v": "4/2",
        "assembly_v": "4/3",
        "meeting": "",
        "on_show": "1",
        "userid": "07074",
        "userDate": "2024-03-29T15:07:13.530Z"
    }
]