function randomIntegerInRange(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

exports.fakedata = [
  {
    Article: "",
    ShoeName: "LIGRA 7 M",
    Line: "GCD_C01",
    Operator: 47,
    TimeCount: 8,
    DepID: "1072",
    Actual_Output: 1583,
    PPH: 4.21,
    RFT: randomIntegerInRange(70,100) ,
    Count_Add: 0,
    Count_Complete: 0,
  },
  {
    Article: "",
    ShoeName: "CRAZYFLIGHT",
    Line: "GCD_C02",
    Operator: 47,
    TimeCount: 8,
    DepID: "1073",
    Actual_Output: 1360,
    PPH: 3.62,
    RFT: randomIntegerInRange(70,100) ,
    Count_Add: 0,
    Count_Complete: 0,
  },
  {
    Article: "",
    ShoeName: "COURT 24",
    Line: "GCD_C03",
    Operator: 35,
    TimeCount: 8,
    DepID: "1074",
    Actual_Output: 1640,
    PPH: 5.86,
    RFT: randomIntegerInRange(70,100) ,
    Count_Add: 0,
    Count_Complete: 0,
  },
  {
    Article: "",
    ShoeName: "D.O.N.",
    Line: "GCD_C04",
    Operator: 48,
    TimeCount: 8,
    DepID: "1075",
    Actual_Output: 1350,
    PPH: 3.52,
    RFT: randomIntegerInRange(70,100) ,
    Count_Add: 0,
    Count_Complete: 0,
  },
  {
    Article: "",
    ShoeName: "GRAND",
    Line: "GCD_C05",
    Operator: 48,
    TimeCount: 8,
    DepID: "1076",
    Actual_Output: 2135,
    PPH: 5.56,
    RFT: randomIntegerInRange(70,100) ,
    Count_Add: 0,
    Count_Complete: 0,
  },
  {
    Article: "",
    ShoeName: "COURT 24",
    Line: "GCD_C08",
    Operator: 31,
    TimeCount: 8,
    DepID: "1089",
    Actual_Output: 1332,
    PPH: 5.37,
    RFT: randomIntegerInRange(70,100) ,
    Count_Add: 0,
    Count_Complete: 0,
  },
  {
    Article: "",
    ShoeName: "CAMPUS 00S W",
    Line: "GCD_C09",
    Operator: 18,
    TimeCount: 8,
    DepID: "1177",
    Actual_Output: 5010,
    PPH: 34.79,
    RFT: randomIntegerInRange(70,100) ,
    Count_Add: 0,
    Count_Complete: 0,
  },

  {
    Article: "",
    ShoeName: "GRAND",
    Line: "GCD_C10",
    Operator: 19,
    TimeCount: 8,
    DepID: "1175",
    Actual_Output: 1537,
    PPH: 10.11,
    RFT: randomIntegerInRange(70,100) ,
    Count_Add: 0,
    Count_Complete: 0,
  },
 

  {
    Article: "",
    ShoeName: "GRAND",
    Line: "GCD_C06",
    Operator: 42,
    TimeCount: 8,
    DepID: "1077",
    Actual_Output: 1390,
    PPH: 4.14,
    RFT: randomIntegerInRange(70,100) ,
    Count_Add: 0,
    Count_Complete: 1,
  },
  {
    Article: "",
    ShoeName: null,
    Line: "GCD_C07",
    Operator: 18,
    TimeCount: 8,
    DepID: "1078",
    Actual_Output: 5605,
    PPH: 38.92,
    RFT: randomIntegerInRange(70,100) ,
    Count_Add: 0,
    Count_Complete: 0,
  },

  {
    Article: "",
    ShoeName: "CAMPUS ADV",
    Line: "GCD_C20",
    Operator: 31,
    TimeCount: 8,
    DepID: "1499",
    Actual_Output: 3121,
    PPH: 12.58,
    RFT: randomIntegerInRange(70,100) ,
    Count_Add: 0,
    Count_Complete: 0,
  },
  {
    Article: "",
    ShoeName: null,
    Line: "GCD_C21",
    Operator: 20,
    TimeCount: 8,
    DepID: "1500",
    Actual_Output: 4343,
    PPH: 27.14,
    RFT: randomIntegerInRange(70,100) ,
    Count_Add: 0,
    Count_Complete: 0,
  },
  {
    Article: "",
    ShoeName: null,
    Line: "GCD_C22",
    Operator: 23,
    TimeCount: 8,
    DepID: "1501",
    Actual_Output: 4601,
    PPH: 25.01,
    RFT: randomIntegerInRange(70,100) ,
    Count_Add: 0,
    Count_Complete: 0,
  },
  {
    Article: "",
    ShoeName: null,
    Line: "GCD_C23",
    Operator: 26,
    TimeCount: 8,
    DepID: "1502",
    Actual_Output: 4855,
    PPH: 23.34,
    RFT: randomIntegerInRange(70,100) ,
    Count_Add: 0,
    Count_Complete: 0,
  },
   {
    Article: "",
    ShoeName: null,
    Line: "GCD_C24",
    Operator: 20,
    TimeCount: 8,
    DepID: "1652",
    Actual_Output: 6006,
    PPH: 37.54,
    RFT: randomIntegerInRange(70,100) ,
    Count_Add: 0,
    Count_Complete: 0,
  },

];


