exports.Data=[
    {
        "Num": "1",
        "Line": "S1",
        "Total_Member": 0,
        "Article": "GZ0069",
        "Model_Name": "LIGRA 7 M",
        "Target": 0,
        "Value_Hour": 0,
        "Hour_8":0,
        "Hour_9":0,
        "Hour_10":0,
        "Hour_11": 0,
        "Hour_12": 0,
        "Hour_13": 0,
        "Hour_14": 0,
        "Hour_15": 0,
        "Total":0,
        "Percent": "0",
        "PPH": 0,
        "RFT": 0,
        "Name_Shift": "CHC"
    },
    {
        "Num": "2",
        "Line": "S2",
        "Total_Member": 0,
        "Article": "IF9257",
        "Model_Name": "CRAZYFLIGHT 5 W MID",
        "Target": 0,
        "Value_Hour":0,
        "Hour_8":0,
        "Hour_9":0,
        "Hour_10":0,
        "Hour_11": 0,
        "Hour_12": 0,
        "Hour_13": 0,
        "Hour_14": 0,
        "Hour_15": 0,
        "Total":0,
        "Percent": "0",
        "PPH": 0,
        "RFT": 0,
        "Name_Shift": "CHC"
    },
    {
        "Num": "3",
        "Line": "S3",
        "Total_Member": 0,
        "Article": "IH0524",
        "Model_Name": "COURT 24",
        "Target": 0,
        "Value_Hour": 0,
        "Hour_8":0,
        "Hour_9":0,
        "Hour_10":0,
        "Hour_11": 0,
        "Hour_12": 0,
        "Hour_13": 0,
        "Hour_14": 0,
        "Hour_15": 0,
        "Total":0,
        "Percent": "0",
        "PPH": 0,
        "RFT": 0,
        "Name_Shift": "CHC"
    },
    {
        "Num": "4",
        "Line": "S4",
        "Total_Member": 0,
        "Article": "IG9087",
        "Model_Name": "D.O.N. ISSUE 6",
        "Target": 0,
        "Value_Hour": 0,
        "Hour_8":0,
        "Hour_9":0,
        "Hour_10":0,
        "Hour_11": 0,
        "Hour_12": 0,
        "Hour_13": 0,
        "Hour_14": 0,
        "Hour_15": 0,
        "Total":0,
        "Percent": "0",
        "PPH": 0,
        "RFT": 0,
        "Name_Shift": "CHC"
    },
    {
        "Num": "5",
        "Line": "S5",
        "Total_Member": 0,
        "Article": "IE1092",
        "Model_Name": "GRAND COURT PLATFORM",
        "Target": 0,
        "Value_Hour": 8,
        "Hour_8":0,
        "Hour_9":0,
        "Hour_10":0,
        "Hour_11": 0,
        "Hour_12": 0,
        "Hour_13": 0,
        "Hour_14": 0,
        "Hour_15": 0,
        "Total":0,
        "Percent": "0",
        "PPH": 0,
        "RFT": 0,
        "Name_Shift": "CHC"
    },
    {
        "Num": "6",
        "Line": "S6",
        "Total_Member": 49,
        "Article": "IF4632",
        "Model_Name": "PUIG",
        "Target": 0,
        "Value_Hour": 8,
        "Hour_8":0,
        "Hour_9":0,
        "Hour_10":0,
        "Hour_11": 0,
        "Hour_12": 0,
        "Hour_13": 0,
        "Hour_14": 0,
        "Hour_15": 0,
        "Total":0,
        "Percent": "45.83",
        "PPH": 1.4,
        "RFT": 75,
        "Name_Shift": "CHC"
    },
    {
        "Num": "7",
        "Line": "S7",
        "Total_Member": 0,
        "Article": "GY0042",
        "Model_Name": "CAMPUS 00S W",
        "Target": 0,
        "Value_Hour": 0,
        "Hour_8":0,
        "Hour_9":0,
        "Hour_10":0,
        "Hour_11": 0,
        "Hour_12": 0,
        "Hour_13": 0,
        "Hour_14": 0,
        "Hour_15": 0,
        "Total":0,
        "Percent": "0",
        "PPH": 0,
        "RFT": 0,
        "Name_Shift": "CHC"
    },
    {
        "Num": "8",
        "Line": "S8",
        "Total_Member": 0,
        "Article": "ID1257",
        "Model_Name": "COURT 24",
        "Target": 0,
        "Value_Hour":0,
        "Hour_8":0,
        "Hour_9":0,
        "Hour_10":0,
        "Hour_11": 0,
        "Hour_12": 0,
        "Hour_13": 0,
        "Hour_14": 0,
        "Hour_15": 0,
        "Total":0,
        "Percent": "61.67",
        "PPH": 2.64,
        "RFT": 76.07,
        "Name_Shift": "CHC"
    },
    {
        "Num": "9",
        "Line": "S9",
        "Total_Member": 0,
        "Article": "IH2659",
        "Model_Name": "CAMPUS 00S W",
        "Target": 0,
        "Value_Hour": 0,
        "Hour_8":0,
        "Hour_9":0,
        "Hour_10":0,
        "Hour_11": 0,
        "Hour_12": 0,
        "Hour_13": 0,
        "Hour_14": 0,
        "Hour_15": 0,
        "Total":0,
        "Percent": "0",
        "PPH": 0,
        "RFT":0,
        "Name_Shift": "CHC"
    },
    {
        "Num": "10",
        "Line": "S10",
        "Total_Member": 0,
        "Article": "IG9159",
        "Model_Name": "CAMPUS 00S J",
        "Target": 0,
        "Value_Hour": 0,
        "Hour_8":0,
        "Hour_9":0,
        "Hour_10":0,
        "Hour_11": 0,
        "Hour_12": 0,
        "Hour_13": 0,
        "Hour_14": 0,
        "Hour_15": 0,
        "Total":0,
        "Percent": "0",
        "PPH": 0,
        "RFT": 0,
        "Name_Shift": "CHC"
    },{
        "Num": "",
        "Line": "Total",
        "Total_Member": 0,
        "Article": "",
        "Model_Name": "",
        "Target": 0,
        "Value_Hour": 0,
        "Hour_8":0,
        "Hour_9":0,
        "Hour_10":0,
        "Hour_11": 0,
        "Hour_12": 0,
        "Hour_13": 0,
        "Hour_14": 0,
        "Hour_15": 0,
        "Total":0,
        "Percent": "",
        "PPH": 0,
        "RFT": 0,
        "Name_Shift": ""
    }
]