export const dataKIP = [
    {
     "ID_QKPI": "A",
     "KPI": "\/Output\/Pairs",
     "Jan": 1871821,
     "Feb": 1457927,
     "Mar": 1355409,
     "Apr": 0,
     "May": 0,
     "Jun": 0,
     "Jul": 0,
     "Aug": 0,
     "Sep": 0,
     "Oct": 0,
     "Nov": 0,
     "Dec": 0,
     "Total": 4685157
    },
    {
     "ID_QKPI": "B",
     "KPI": "\/Material\/FGT Test USD",
     "Jan": 4073.78,
     "Feb": 1796.8,
     "Mar": 0,
     "Apr": 0,
     "May": 0,
     "Jun": 0,
     "Jul": 0,
     "Aug": 0,
     "Sep": 0,
     "Oct": 0,
     "Nov": 0,
     "Dec": 0,
     "Total": 5870.58
    },
    {
     "ID_QKPI": "C",
     "KPI": "\/Material\/FGT Retest USD",
     "Jan": 12.4,
     "Feb": 4.69,
     "Mar": 0,
     "Apr": 0,
     "May": 0,
     "Jun": 0,
     "Jul": 0,
     "Aug": 0,
     "Sep": 0,
     "Oct": 0,
     "Nov": 0,
     "Dec": 0,
     "Total": 17.09
    },
    {
     "ID_QKPI": "D",
     "KPI": "\/3rd Party Testing Fee USD",
     "Jan": 223.65,
     "Feb": 263.69,
     "Mar": 0,
     "Apr": 0,
     "May": 0,
     "Jun": 0,
     "Jul": 0,
     "Aug": 0,
     "Sep": 0,
     "Oct": 0,
     "Nov": 0,
     "Dec": 0,
     "Total": 487.34
    },
    {
     "ID_QKPI": "DR",
     "KPI": "\/DR\/Pair",
     "Jan": 1188,
     "Feb": 722,
     "Mar": 0,
     "Apr": 0,
     "May": 0,
     "Jun": 0,
     "Jul": 0,
     "Aug": 0,
     "Sep": 0,
     "Oct": 0,
     "Nov": 0,
     "Dec": 0,
     "Total": 1910
    },
    {
     "ID_QKPI": "E",
     "KPI": "\/3rd Party Inspection Fee USD",
     "Jan": 0,
     "Feb": 0,
     "Mar": 0,
     "Apr": 0,
     "May": 0,
     "Jun": 0,
     "Jul": 0,
     "Aug": 0,
     "Sep": 0,
     "Oct": 0,
     "Nov": 0,
     "Dec": 0,
     "Total": 0
    },
    {
     "ID_QKPI": "F",
     "KPI": "\/DR\/USD",
     "Jan": 22684.5,
     "Feb": 14422.37,
     "Mar": 0,
     "Apr": 0,
     "May": 0,
     "Jun": 0,
     "Jul": 0,
     "Aug": 0,
     "Sep": 0,
     "Oct": 0,
     "Nov": 0,
     "Dec": 0,
     "Total": 37106.87
    },
    {
     "ID_QKPI": "G",
     "KPI": "\/Claim\/USD",
     "Jan": 1229.66,
     "Feb": 0,
     "Mar": 0,
     "Apr": 0,
     "May": 0,
     "Jun": 0,
     "Jul": 0,
     "Aug": 0,
     "Sep": 0,
     "Oct": 0,
     "Nov": 0,
     "Dec": 0,
     "Total": 1229.66
    },
    {
     "ID_QKPI": "H",
     "KPI": "\/Repacking",
     "Jan": 181507,
     "Feb": 225730,
     "Mar": 238476,
     "Apr": 0,
     "May": 0,
     "Jun": 0,
     "Jul": 0,
     "Aug": 0,
     "Sep": 0,
     "Oct": 0,
     "Nov": 0,
     "Dec": 0,
     "Total": 645713
    },
    {
     "ID_QKPI": "I",
     "KPI": "\/USD Cost Per Pair",
     "Jan": 0.0075,
     "Feb": 0.0021,
     "Mar": 0,
     "Apr": 0,
     "May": 0,
     "Jun": 0,
     "Jul": 0,
     "Aug": 0,
     "Sep": 0,
     "Oct": 0,
     "Nov": 0,
     "Dec": 0,
     "Total": 0.0096
    },
    {
     "ID_QKPI": "J",
     "KPI": "\/DR Per Pair\/USD",
     "Jan": 0.0193,
     "Feb": 0.0136,
     "Mar": 0,
     "Apr": 0,
     "May": 0,
     "Jun": 0,
     "Jul": 0,
     "Aug": 0,
     "Sep": 0,
     "Oct": 0,
     "Nov": 0,
     "Dec": 0,
     "Total": 0.0329
    },
    {
     "ID_QKPI": "K",
     "KPI": "\/Claim Per Pair\/USD",
     "Jan": 0.0016,
     "Feb": 0,
     "Mar": 0,
     "Apr": 0,
     "May": 0,
     "Jun": 0,
     "Jul": 0,
     "Aug": 0,
     "Sep": 0,
     "Oct": 0,
     "Nov": 0,
     "Dec": 0,
     "Total": 0.0016
    },
    {
     "ID_QKPI": "L",
     "KPI": "\/Repacking Per Pair\/%",
     "Jan": 0.1604,
     "Feb": 0.2235,
     "Mar": 0.2312,
     "Apr": 0,
     "May": 0,
     "Jun": 0,
     "Jul": 0,
     "Aug": 0,
     "Sep": 0,
     "Oct": 0,
     "Nov": 0,
     "Dec": 0,
     "Total": 0.6151
    }
   ]